### ISSUE TITLE
HTML assignment problem

### ISSUE THREAD

**Issue by greenw14** [learn-co-curriculum/phase-0-completing-assignments#10]
My bundle command does not work when I try to use it in terminal. It says "could not locate Gemfile" and when I run rspec it says "zsh: command not found: rspec". Is there any fix for this?

**Comment by ihollander** [comment]
Thanks for raising this issue. Based on your description, it sounds like the issue may be related to your environment setup or the way you are attempting to run the code for this lab rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
