### ISSUE TITLE
Fork button points to Canvas home page (https://base.flatironschool.com/)

### ISSUE THREAD

**Issue by AnneElizabeth** [learn-co-curriculum/phase-0-completing-assignments#34]
### Canvas Link

https://learning.flatironschool.com/courses/5647/assignments/190292?module_item_id=425114

### Concern

Click on the fork button takes me to the Canvas home page instead of github. Test passes when I manually complete the assignment; however, it doesn't show as complete.

**Comment by lizbur10** [comment]
Hi @AnneElizabeth - so sorry to hear you're having issues. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support. To get help with this, you can use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team.
